spring.application.name=parking
spring.datasource.username=${SPRING_DATA_USERNAME:root}
spring.datasource.password=${SPRING_DATA_PASSWORD:Dai@12345678}
spring.datasource.url=${SPRING_DATA_URL:jdbc:mysql://localhost:3306/parking_management}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=none

#spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
api.v1.prefix=/api
#loging
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.cache=DEBUG
logging.level.org.hibernate.start=DEBUG
spring.jpa.properties.hibernate.type=trace
spring.jackson.serialization.fail-on-empty-beans=false
#log4j.logger.org.hibernate.SQL=DEBUG
#log4j.logger.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=com.project.parking.controller
cloudinary.cloud-name=dmuhayimh
cloudinary.api-key=158318969485565
cloudinary.api-secret=INfYz9o6GoyIwNMw-gFfiKvqb7Q

jwt.secret.key=trandai
spring.jackson.time-zone=Asia/Ho_Chi_Minh

#Plate recognizer
platerecognizer.api.url=https://api.platerecognizer.com/v1/plate-reader/
platerecognizer.api.key=0471e378e5ee2fb08589d814bcc59550d69d9854
# Spring mail
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=api
spring.mail.password=d9b182788c89a8170b9f62bf03a21cfc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.localhost=localhost
spring.mail.properties.mail.smtp.from=no-reply@thinhtran.space
spring.mail.protocol=smtp
mail.debug=true

#redis
spring.cache.type=redis
spring.data.redis.host=${REDIS.HOST:localhost}
spring.data.redis.port=${REDIS.PORT:6379}
spring.cache.redis.time-to-live=3600000

#momo
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partnerCode=MOMOBKUN20180529
momo.accessKey=klm05TvNBzhg7h7j
momo.secretKey=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa

redirectUrl=${REDIRECT_URL:http://localhost:3000/payment-return}
ipUrl=${IP_URL:https://localhost:8080/api/v1/payments/ipn}
